<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5330bc69-14e9-4bd3-b61b-e0b462515741</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Application\Settings\**" />
    <Compile Remove="Infrastructure\Data\**" />
    <Compile Remove="test_dataset\**" />
    <Content Remove="Application\Settings\**" />
    <Content Remove="Infrastructure\Data\**" />
    <Content Remove="test_dataset\**" />
    <EmbeddedResource Remove="Application\Settings\**" />
    <EmbeddedResource Remove="Infrastructure\Data\**" />
    <EmbeddedResource Remove="test_dataset\**" />
    <None Remove="Application\Settings\**" />
    <None Remove="Infrastructure\Data\**" />
    <None Remove="test_dataset\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.k6" Version="13.4.0" />
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Hangfire" Version="1.8.24" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="10.0.11" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="PeNet" Version="5.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="8.0.0" />
  </ItemGroup>

</Project>
